output "cluster_name" {
  description = "kind cluster name"
  value       = resource.kind_cluster.default.name
}

output "cluster_endpoint" {
  description = "Endpoint for kind control plane."
  value       = resource.kind_cluster.default.endpoint
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = resource.kind_cluster.default.kubeconfig
}
