apiVersion: v1
kind: Service
metadata:
  name: db-postgresql
  labels:
    app: db-postgresql
spec:
  type: NodePort
  selector:
   app: db-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432